name: flutterfall
description: "A Flutter package to create falling effects using custom images."
version: 1.0.6
homepage: https://github.com/rvdrover/flutterfall
repository: https://github.com/rvdrover/flutterfall
issue_tracker: https://github.com/rvdrover/flutterfall/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

